/**
 * NodeKind enum → stable string names for golden parity vs TS baseline.
 */
import { NodeKind } from './types.js'

const KIND_NAMES: Record<NodeKind, string> = {
	[NodeKind.Program]: 'Program',
	[NodeKind.VariableDeclaration]: 'VariableDeclaration',
	[NodeKind.VariableDeclarator]: 'VariableDeclarator',
	[NodeKind.FunctionDeclaration]: 'FunctionDeclaration',
	[NodeKind.ClassDeclaration]: 'ClassDeclaration',
	[NodeKind.ImportDeclaration]: 'ImportDeclaration',
	[NodeKind.ExportDeclaration]: 'ExportDeclaration',
	[NodeKind.BlockStatement]: 'BlockStatement',
	[NodeKind.ExpressionStatement]: 'ExpressionStatement',
	[NodeKind.IfStatement]: 'IfStatement',
	[NodeKind.ForStatement]: 'ForStatement',
	[NodeKind.ForInStatement]: 'ForInStatement',
	[NodeKind.ForOfStatement]: 'ForOfStatement',
	[NodeKind.WhileStatement]: 'WhileStatement',
	[NodeKind.DoWhileStatement]: 'DoWhileStatement',
	[NodeKind.SwitchStatement]: 'SwitchStatement',
	[NodeKind.SwitchCase]: 'SwitchCase',
	[NodeKind.ReturnStatement]: 'ReturnStatement',
	[NodeKind.ThrowStatement]: 'ThrowStatement',
	[NodeKind.TryStatement]: 'TryStatement',
	[NodeKind.CatchClause]: 'CatchClause',
	[NodeKind.BreakStatement]: 'BreakStatement',
	[NodeKind.ContinueStatement]: 'ContinueStatement',
	[NodeKind.EmptyStatement]: 'EmptyStatement',
	[NodeKind.Identifier]: 'Identifier',
	[NodeKind.Literal]: 'Literal',
	[NodeKind.ArrayExpression]: 'ArrayExpression',
	[NodeKind.ObjectExpression]: 'ObjectExpression',
	[NodeKind.Property]: 'Property',
	[NodeKind.FunctionExpression]: 'FunctionExpression',
	[NodeKind.ArrowFunctionExpression]: 'ArrowFunctionExpression',
	[NodeKind.ClassExpression]: 'ClassExpression',
	[NodeKind.CallExpression]: 'CallExpression',
	[NodeKind.NewExpression]: 'NewExpression',
	[NodeKind.MemberExpression]: 'MemberExpression',
	[NodeKind.BinaryExpression]: 'BinaryExpression',
	[NodeKind.UnaryExpression]: 'UnaryExpression',
	[NodeKind.UpdateExpression]: 'UpdateExpression',
	[NodeKind.AssignmentExpression]: 'AssignmentExpression',
	[NodeKind.LogicalExpression]: 'LogicalExpression',
	[NodeKind.ConditionalExpression]: 'ConditionalExpression',
	[NodeKind.SequenceExpression]: 'SequenceExpression',
	[NodeKind.SpreadElement]: 'SpreadElement',
	[NodeKind.TemplateLiteral]: 'TemplateLiteral',
	[NodeKind.TaggedTemplateExpression]: 'TaggedTemplateExpression',
	[NodeKind.ThisExpression]: 'ThisExpression',
	[NodeKind.Super]: 'Super',
	[NodeKind.AwaitExpression]: 'AwaitExpression',
	[NodeKind.YieldExpression]: 'YieldExpression',
	[NodeKind.ArrayPattern]: 'ArrayPattern',
	[NodeKind.ObjectPattern]: 'ObjectPattern',
	[NodeKind.AssignmentPattern]: 'AssignmentPattern',
	[NodeKind.RestElement]: 'RestElement',
	[NodeKind.ImportSpecifier]: 'ImportSpecifier',
	[NodeKind.ImportDefaultSpecifier]: 'ImportDefaultSpecifier',
	[NodeKind.ImportNamespaceSpecifier]: 'ImportNamespaceSpecifier',
	[NodeKind.ExportSpecifier]: 'ExportSpecifier',
	[NodeKind.MethodDefinition]: 'MethodDefinition',
	[NodeKind.PropertyDefinition]: 'PropertyDefinition',
	[NodeKind.Comment]: 'Comment',
}

export function nodeKindName(kind: NodeKind): string {
	return KIND_NAMES[kind] ?? `Unknown(${kind})`
}