name: Release

on:
  push:
    branches: [main]

jobs:
  release:
    permissions:
      actions: write
      contents: write
      pull-requests: write
      id-token: write
    uses: SylphxAI/.github/.github/workflows/release.yml@main
    with:
      build: |
        rustup target add wasm32-unknown-unknown
        curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
        export PATH="$HOME/.cargo/bin:$PATH"
        bunx turbo build --concurrency=1
    secrets: inherit
